AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  HangJS:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.hello
      Runtime: nodejs6.10
      CodeUri: .
      Timeout: 5
      MemorySize: 128
      Environment:
        Variables:
          MemorySize: 128
          Ratio: 0.16
